# Generated by Django 2.2.6 on 2019-10-15 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('add', '__first__'),
        ('join', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseAttach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.URLField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='course/')),
                ('desc', models.TextField(blank=True, null=True)),
                ('public', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('startdate', models.DateField()),
                ('endtdate', models.DateField()),
                ('starttime', models.TimeField()),
                ('endtime', models.TimeField()),
                ('signup', models.URLField(blank=True, null=True)),
                ('intro', models.TextField(blank=True, null=True)),
                ('other', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('YET', '尚未開始'), ('END', '課程結束'), ('HIDE', '隱藏')], default='HIDE', max_length=10)),
                ('attachs', models.ManyToManyField(blank=True, null=True, to='course.CourseAttach')),
                ('attendees', models.ManyToManyField(blank=True, null=True, to='join.Attendee')),
                ('categorys', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='add.Category')),
                ('locations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='add.Location')),
                ('members', models.ManyToManyField(blank=True, null=True, to='join.Member')),
                ('teachers', models.ManyToManyField(to='add.Teacher')),
            ],
        ),
    ]
