# Generated by Django 2.2.4 on 2019-08-22 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('nid', models.CharField(max_length=15, unique=True)),
                ('dept', models.CharField(max_length=20)),
                ('level', models.CharField(choices=[('B1', 'freshman'), ('B2', 'sophomore'), ('B3', 'junior'), ('B4', 'senior'), ('M1', 'first year of graduate school'), ('M2', 'second year of graduate school')], max_length=2)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('status', models.CharField(choices=[('UR', 'under review'), ('M', 'member'), ('NP', 'non-payment')], default='UR', max_length=2)),
            ],
        ),
    ]
